version: '3.8'

services:

  eureka:
    build: ./cloud-eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    build:
      context: ./user
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/

  project-service:
    build:
      context: ./project
    ports:
      - "8084:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/

  template-service:
    build:
      context: ./template
    ports:
      - "8082:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/

  gen-service:
    build:
      context: ./gen
    ports:
      - "8083:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/

  gateway-service:
    build:
      context: ./gateway
    ports:
      - "8888:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - gateway-service
    environment:
      - API_BASE_URL=http://gateway-service:8888 # Use this for frontend API calls

networks:
  app-network:
    driver: bridge
